### ISSUE TITLE
Inventory plugin: Remote is hardcoded to 'local'

### ISSUE THREAD

**Issue by cfenell** [kmpm/ansible-collection-incus#13]
In inventory/incus.py line 128:
`cli = IncusClient(remote='local', project=self.project, debug=True)`

As the Ansible control node is, in general, not one of the Incus hosts, I would like to be able to specify the remote/s.

**Comment by kmpm** [comment]
Should hopefully be fixed but I don't have a test environment to verify it. Please reopen if needed.
